---
title: "Playing with Priors"
author: "Mariana Arrieta Yanez"
date: "7/5/2021"
output: html_document
---


```{r}

model_w_priors_arg_2019 <- bsts_run_w_prior(y = train_arg$cc, 
                                            model_spec = cc ~ ., 
                                            seasons = 12, 
                                            iterations = 20000, 
                                            train_df = train_arg, 
                                            initial_year = 2017)

model_w_priors_arg_2021 <- bsts_run_w_prior(y = train_arg_21$cc, 
                                            model_spec = cc ~ ., 
                                            seasons = 12, 
                                            iterations = 20000, 
                                            train_df = train_arg_21, 
                                            initial_year = 2019)
```

```{r}
pred_w_priors_arg_2019 <- prediction_df_and_plot(model= model_w_priors_arg_2019, 
                                              pred_horizon= 3, 
                                              full_df= df_arg_2019, 
                                              train_df= train_arg, 
                                              test_df= test_arg, 
                                              reg= TRUE, 
                                              prior = TRUE)

pred_w_priors_arg_2019$plot

get_errors(MAPE_df = pred_w_priors_arg_2019$MAPE_raw, test_year = 2019, country = "argentina", reg = TRUE)

### 2021 ####
pred_w_priors_arg_2021 <- prediction_df_and_plot(model= model_w_priors_arg_2021, 
                                              pred_horizon= 3, 
                                              full_df= df_arg_2021, 
                                              train_df= train_arg_21, 
                                              test_df= test_arg_21, 
                                              test_year= 2021,
                                              reg= TRUE,
                                              prior = TRUE)

pred_w_priors_arg_2021$plot

get_errors(MAPE_df = pred_w_priors_arg_2021$MAPE_raw, test_year = 2021, country = "argentina", reg = TRUE)
```


```{r}
var_inclusion_bsts(model_w_priors_arg_2019)
var_inclusion_bsts(model_w_priors_arg_2021)
```
```{r}
param_values_bsts(model_w_priors_arg_2019, tolerance_level = 0.001)

param_values_bsts(model_w_priors_arg_2021, tolerance_level = 0.001)
```

```{r}
### BRASIL ###
model_w_priors_bra_2019 <- bsts_run_w_prior(y = train_bra$cc, 
                                            model_spec = cc ~ ., 
                                            seasons = 12, 
                                            iterations = 20000, 
                                            train_df = train_bra, 
                                            initial_year = 2017)

model_w_priors_bra_2021 <- bsts_run_w_prior(y = train_bra_21$cc, 
                                            model_spec = cc ~ ., 
                                            seasons = 12, 
                                            iterations = 20000, 
                                            train_df = train_bra_21, 
                                            initial_year = 2019)

param_values_bsts(model_w_priors_bra_2019, tolerance_level = 0.001)


param_values_bsts(model_w_priors_bra_2021, tolerance_level = 0.001)
```
```{r}
pred_w_priors_bra_2019 <- prediction_df_and_plot(model= model_w_priors_bra_2019, 
                                              pred_horizon= 3, 
                                              full_df= df_bra_2019, 
                                              train_df= train_bra, 
                                              test_df= test_bra, 
                                              reg= TRUE, 
                                              prior = TRUE)

pred_w_priors_bra_2019$plot

get_errors(MAPE_df = pred_w_priors_bra_2019$MAPE_raw, test_year = 2019, country = "brasil", reg = TRUE)

### 2021 ####
pred_w_priors_bra_2021 <- prediction_df_and_plot(model= model_w_priors_bra_2021, 
                                              pred_horizon= 3, 
                                              full_df= df_bra_2021, 
                                              train_df= train_bra_21, 
                                              test_df= test_bra_21, 
                                              test_year = 2021,
                                              reg= TRUE, 
                                              prior = TRUE)

pred_w_priors_bra_2021$plot

get_errors(MAPE_df = pred_w_priors_bra_2021$MAPE_raw, test_year = 2021, country = "brasil", reg = TRUE)
```
```{r}
param_values_bsts(model_w_priors_bra_2019, tolerance_level = 0.001)

param_values_bsts(model_w_priors_bra_2021, tolerance_level = 0.001)
```


```{r}
## CHILE ###

model_w_priors_chi_2019 <- bsts_run_w_prior(y = train_chi$cc, 
                                            model_spec = cc ~ ., 
                                            seasons = 12, 
                                            iterations = 20000, 
                                            train_df = train_chi, 
                                            initial_year = 2017)

model_w_priors_chi_2021 <- bsts_run_w_prior(y = train_chi_21$cc, 
                                            model_spec = cc ~ ., 
                                            seasons = 12, 
                                            iterations = 20000, 
                                            train_df = train_chi_21, 
                                            initial_year = 2019)
```

```{r}
pred_w_priors_chi_2019 <- prediction_df_and_plot(model= model_w_priors_chi_2019, 
                                              pred_horizon= 3, 
                                              full_df= df_chi_2019, 
                                              train_df= train_chi, 
                                              test_df= test_chi, 
                                              reg= TRUE, 
                                              prior = TRUE)

pred_w_priors_chi_2019$plot

get_errors(MAPE_df = pred_w_priors_chi_2019$MAPE_raw, test_year = 2019, country = "chile", reg = TRUE)

### 2021 ####
pred_w_priors_chi_2021 <- prediction_df_and_plot(model= model_w_priors_chi_2021, 
                                              pred_horizon= 3, 
                                              full_df= df_chi_2021, 
                                              train_df= train_chi_21, 
                                              test_df= test_chi_21,
                                              test_year = 2021,
                                              reg= TRUE, 
                                              prior = TRUE)

pred_w_priors_chi_2021$plot

get_errors(MAPE_df = pred_w_priors_chi_2021$MAPE_raw, test_year = 2021, country = "chile", reg = TRUE)
```
```{r}
param_values_bsts(model_w_priors_chi_2019, tolerance_level = 0.001)

param_values_bsts(model_w_priors_chi_2021, tolerance_level = 0.001)
```

```{r}
#### COLOMBIA ### 

model_w_priors_col_2019 <- bsts_run_w_prior(y = train_col$cc, 
                                            model_spec = cc ~ ., 
                                            seasons = 12, 
                                            iterations = 20000, 
                                            train_df = train_col, 
                                            initial_year = 2017)

model_w_priors_col_2021 <- bsts_run_w_prior(y = train_col_21$cc, 
                                            model_spec = cc ~ ., 
                                            seasons = 12, 
                                            iterations = 20000, 
                                            train_df = train_col_21, 
                                            initial_year = 2019)
```

```{r}
pred_w_priors_col_2019 <- prediction_df_and_plot(model= model_w_priors_col_2019, 
                                              pred_horizon= 3, 
                                              full_df= df_col_2019, 
                                              train_df= train_col, 
                                              test_df= test_col,
                                              prior = TRUE,
                                              reg= TRUE)

pred_w_priors_col_2019$plot

get_errors(MAPE_df = pred_w_priors_col_2019$MAPE_raw, test_year = 2019, country = "colombia", reg = TRUE)

### 2021 ####
pred_w_priors_col_2021 <- prediction_df_and_plot(model= model_w_priors_col_2021, 
                                              pred_horizon= 3, 
                                              full_df= df_col_2021, 
                                              train_df= train_col_21, 
                                              test_df= test_col_21, 
                                              test_year = 2021,
                                              prior = TRUE,
                                              reg= TRUE)

pred_w_priors_col_2021$plot

get_errors(MAPE_df = pred_w_priors_col_2021$MAPE_raw, test_year = 2021, country = "colombia", reg = TRUE)
```
```{r}
param_values_bsts(model_w_priors_col_2019, tolerance_level = 0.001)

param_values_bsts(model_w_priors_col_2021, tolerance_level = 0.001)
```

```{r}
### MEXICO ###

model_w_priors_mex_2019 <- bsts_run_w_prior(y = train_mex$cc, 
                                            model_spec = cc ~ ., 
                                            seasons = 12, 
                                            iterations = 20000, 
                                            train_df = train_mex, 
                                            initial_year = 2017)

model_w_priors_mex_2021 <- bsts_run_w_prior(y = train_mex_21$cc, 
                                            model_spec = cc ~ ., 
                                            seasons = 12, 
                                            iterations = 20000, 
                                            train_df = train_mex_21, 
                                            initial_year = 2019)
```

```{r}
pred_w_priors_mex_2019 <- prediction_df_and_plot(model= model_w_priors_mex_2019, 
                                              pred_horizon= 3, 
                                              full_df= df_mex_2019, 
                                              train_df= train_mex, 
                                              test_df= test_mex, 
                                              reg= TRUE, 
                                              prior = TRUE)

pred_w_priors_mex_2019$plot

get_errors(MAPE_df = pred_w_priors_mex_2019$MAPE_raw, test_year = 2019, country = "mexico", reg = TRUE)

### 2021 ####
pred_w_priors_mex_2021 <- prediction_df_and_plot(model= model_w_priors_mex_2021, 
                                              pred_horizon= 3, 
                                              full_df= df_mex_2021, 
                                              train_df= train_mex_21, 
                                              test_df= test_mex_21, 
                                              test_year = 2021, 
                                              prior = TRUE,
                                              reg= TRUE)

pred_w_priors_mex_2021$plot

get_errors(MAPE_df = pred_w_priors_mex_2021$MAPE_raw, test_year = 2021, country = "mexico", reg = TRUE)
```

```{r}
param_values_bsts(model_w_priors_mex_2019, tolerance_level = 0.001)

param_values_bsts(model_w_priors_mex_2021, tolerance_level = 0.001)
```

